### ISSUE TITLE
Py 12 support?

### ISSUE THREAD

**Issue by dlroy88osu** [CristiFati/pyaudio#2]
Works great on 11 but are you doing anything to port to 12 or is there a workaround?

(.venv) PS C:\Users\DanielRoy\Documents\GitHub\ProjectProdigi\3.12> pip install pyaudio
Collecting pyaudio
  Using cached PyAudio-0.2.13.tar.gz (46 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "c:\Users\DanielRoy\Documents\GitHub\ProjectProdigi\3.12\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>    
          main()
        File "c:\Users\DanielRoy\Documents\GitHub\ProjectProdigi\3.12\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main        
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\Users\DanielRoy\Documents\GitHub\ProjectProdigi\3.12\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "c:\Users\DanielRoy\Documents\GitHub\ProjectProdigi\3.12\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\DanielRoy\AppData\Local\Temp\pip-build-env-k9y76732\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\DanielRoy\AppData\Local\Temp\pip-build-env-k9y76732\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\DanielRoy\AppData\Local\Temp\pip-build-env-k9y76732\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by markferry** [comment]
Revert 40577822c305041ce424935268022b21f968cc93

The issue is caused by the old version of setuptools that pyaudio restricts itself to.

Remove the restriction and the mac armv8 version builds (python3.7 and `setuptools==68.0.0`) so it may no longer be necessary. I don't have access to an x86_64 mac though.

**Comment by CristiFati** [comment]
I pulled last changes from upstream, and there seems to be a commit related to *Python 3.12*.

**Comment by markferry** [comment]
And 3.12 wheels are out too! \o/
https://pypi.org/project/PyAudio/#files

**Comment by cclauss** [comment]
I believe that Python 3.12 is fixed but Python 3.13 on Windows is not.
* #9

**Comment by CristiFati** [comment]
Wheels available at https://pypi.org/project/PyAudio.
