### ISSUE TITLE
Regression from 0.2.13 to 0.2.14

### ISSUE THREAD

**Issue by bliep** [CristiFati/pyaudio#4]
In 0.2.14 I get the following error on MacOS:
```
||PaMacCore (AUHAL)|| AUHAL component not found.Traceback (most recent call last):
  File "/Users/adev/src/audio_engineering/tools/player.py", line 58, in <module>
    play(args.path, args.output_device, args.volume)
  File "/Users/adev/src/audio_engineering/tools/player.py", line 32, in play
    stream = p.open(
  File "/Users/adev/miniconda3/lib/python3.10/site-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "/Users/adev/miniconda3/lib/python3.10/site-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9999] Unanticipated host error
```

All is well on 0.2.13, something has broken in 0.2.14. My version of portaudio hasn't changed (portaudio: stable 19.7.0)

**Comment by bliep** [comment]
Fluke
